name: pinterest
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # ------------------ UI & Design ------------------
  cupertino_icons: ^1.0.6
  google_nav_bar: ^5.0.6
  smooth_page_indicator: any
  shimmer: any
  flutter_svg: ^2.2.3
  lottie: any
  flutter_blur: any
  liquid_glass: ^0.0.1
  tutorial_coach_mark: ^1.3.1
  flutter_otp_text_field: ^1.5.1+1

  # ------------------ State Management & Storage ------------------
  get: ^4.6.6
  get_storage: ^2.1.1
  shared_preferences: ^2.5.4

  # ------------------ Networking & API ------------------
  http: ^1.2.2
  supabase_flutter: any
  flutter_dotenv: ^5.1.0

  # ------------------ Media & Image Handling ------------------
  image_picker: ^1.0.7
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.3.1
  flutter_staggered_grid_view: any

  # ------------------ Device & Permissions ------------------
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  path_provider: ^2.1.3
  visibility_detector: ^0.4.0+2
  gradient_icon: 
  google_fonts: 
  


  # ------------------ Web & External Content ------------------
  webview_flutter: any

  # ------------------ App Icon ------------------
  flutter_launcher_icons: any

  # ------------------ Extra Features ------------------
  share_plus: ^10.0.0
  intl: ^0.19.0
  package_info_plus: ^8.3.1
  video_player: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - Assets/

  fonts:
    - family: Chillax
      fonts:
        - asset: Assets/font/Chillax-TTF/Chillax-Regular.ttf
        - asset: Assets/font/Chillax-TTF/Chillax-Bold.ttf
          weight: 700
        - asset: Assets/font/Chillax-TTF/Chillax-Medium.ttf
          weight: 500
        - asset: Assets/font/Chillax-TTF/Chillax-Light.ttf
          weight: 300
        - asset: Assets/font/Chillax-TTF/Chillax-Extralight.ttf
          weight: 200
        - asset: Assets/font/Chillax-TTF/Chillax-Semibold.ttf
          weight: 600

    - family: Quicksand
      fonts:
        - asset: Assets/font/Quicksand_Complete/Quicksand_Complete/Fonts/TTF/Quicksand-Variable.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "Assets/swan.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "Assets/swan.png"
remove_alpha_ios: true